### ISSUE TITLE
Question: Attribute not supported when reading description of an object

### ISSUE THREAD

**Issue by rjboer** [awcullen/opcua#10]
When trying to read the discription of an object,  
I get the following response: <nil> The attribute is not supported for the specified Node.

The snippet works for other nodes (variables)
It also doesn't work when refering to the the object through its identifier

req := &ua.ReadRequest{
		NodesToRead: []ua.ReadValueID{
			{
				NodeID:      ua.ParseNodeID("ns=4;s=IdentificationData"),
				AttributeID: ua.AttributeIDDescription,
			},
		},
	}

![image](https://user-images.githubusercontent.com/14197553/208915368-fa973fc4-4640-4e0f-bfb8-f3dfbd8b5798.png)

**Comment by rjboer** [comment]
Browsing that same object does not work either...

Browse results of NodeID 's=IdentificationData':

contents of resultstruct{The node id refers to a node that does not exist in the server address space.  []}

ns4;s=IdentificationData and ns4;i=463 gives the same result

While in Node-Red and with the C++ open62541 this does work

**Comment by rjboer** [comment]
Datatype scan of node: ns=4;i=467
scanmask: 1, statuscode:The operation completed successfully., value:ns=4;i=467
scanmask: 2, statuscode:The operation completed successfully., value:64
scanmask: 3, statuscode:The operation completed successfully., value:4:UDT_SemVer
scanmask: 4, statuscode:The operation completed successfully., value:UDT_SemVer
scanmask: 5, statuscode:The attribute is not supported for the specified Node., value:<nil>
scanmask: 6, statuscode:The operation completed successfully., value:0
scanmask: 7, statuscode:The operation completed successfully., value:0
scanmask: 8, statuscode:The operation completed successfully., value:false
scanmask: 9, statuscode:The attribute is not supported for the specified Node., value:<nil>
scanmask: 10, statuscode:The attribute is not supported for the specified Node., value:<nil>
scanmask: 11, statuscode:The attribute is not supported for the specified Node., value:<nil>
scanmask: 12, statuscode:The attribute is not supported for the specified Node., value:<nil>
scanmask: 13, statuscode:The attribute is not supported for the specified Node., value:<nil>
scanmask: 14, statuscode:The attribute is not supported for the specified Node., value:<nil>
scanmask: 15, statuscode:The attribute is not supported for the specified Node., value:<nil>
scanmask: 16, statuscode:The attribute is not supported for the specified Node., value:<nil>
scanmask: 17, statuscode:The attribute is not supported for the specified Node., value:<nil>
scanmask: 18, statuscode:The attribute is not supported for the specified Node., value:<nil>
scanmask: 19, statuscode:The attribute is not supported for the specified Node., value:<nil>
scanmask: 20, statuscode:The attribute is not supported for the specified Node., value:<nil>
scanmask: 21, statuscode:The attribute is not supported for the specified Node., value:<nil>
scanmask: 22, statuscode:The attribute is not supported for the specified Node., value:<nil>
scanmask: 23, statuscode:The operation completed successfully., value:{ns=4;i=468 ns=3;i=3400 Structure [{major  i=3 -1 [] 0 false} {minor  i=3 -1 [] 0 false} {patch  i=3 -1 [] 0 false}]}
scanmask: 24, statuscode:The attribute is not supported for the specified Node., value:<nil>
scanmask: 25, statuscode:The attribute is not supported for the specified Node., value:<nil>
scanmask: 26, statuscode:The attribute is not supported for the specified Node., value:0
scanmask: 27, statuscode:The attribute is not supported for the specified Node., value:<nil>

**Comment by awcullen** [comment]
Hi @rjboer, thanks for trying the library.

You found that nodes have NodeClass attribute, and if NodeClass is Variable, the node will have Value, DataType, and ValueRank attributes.  You found the DataType can be a 'built-in' type or complex structure. ValueRank can tell you if it is a slice. 

Sometime the UA server will describe the structure in the DataTypeDefinition attribute.  This library does not yet have a feature to use that definition.

Sometimes the UA server will provide NodeIDs for the components of the structure so that you can read the component parts. If the components are 'built-in' types, then this may be sufficient for you.

You can also try to create your own public struct and register it with the library.  For instance:
```
type SemVerDataType struct {
	Major uint8
	Minor uint8
	Patch uint8
}

func init() {
    ua.RegisterBinaryEncodingID(reflect.TypeOf(SemVerDataType{}), ua.NewExpandedNodeID(ua.ParseNodeID("ns=4;i=468")))
}
```

Then when you read a variable of the 'SemVer' datatype, the library will decode it. You just have to cast the Value to your type:
```
	if semVer, ok := res.Results[0].Value.(SemVerDataType); ok {

```

**Comment by mark-resato** [comment]
i tried something similar to rjboer, with the following code

```go
package main

import (
    "context"
    "fmt"
    "github.com/awcullen/opcua/client"
    "github.com/awcullen/opcua/ua"
    "reflect"
)

type CustomStruct struct {
    W1 uint16
    W2 uint16
}

func init() {
    ua.RegisterBinaryEncodingID(reflect.TypeOf(CustomStruct{}), ua.NewExpandedNodeID(ua.ParseNodeID("ns=4;i=14")))
}

func main() {
    ctx := context.Background()
    ch, err := client.Dial(
        ctx,
        "opc.tcp://50.50.50.1:4840",
        client.WithInsecureSkipVerify(), // skips verification of server certificate
    )
    if err != nil {
        fmt.Printf("Error opening client connection. %s\n", err.Error())
        return
    }
    
    // read single data value
    readRequest := &ua.ReadRequest{
        NodesToRead: []ua.ReadValueID{
            {
                NodeID:      ua.ParseNodeID(fmt.Sprintf("ns=4;i=14")),
                AttributeID: ua.AttributeIDValue,
            },
        },
    }
    readResponse, err := ch.Read(ctx, readRequest)
    if err != nil {
        fmt.Println("read error:", err)
        return
    }
    
    // print the read result(s)
    for _, v := range readResponse.Results {
        fmt.Println(v)
        fmt.Printf("Type: %T, value: %v, %v \n", v.Value, v.Value, v.StatusCode)
    }
    if semVer, ok := readResponse.Results[0].Value.(CustomStruct); ok {
        fmt.Println(semVer)
    } else {
        fmt.Println("result is not of custom type")
    }
}
```
when i run this i get the following result 
```
{<nil> The operation completed successfully. 2023-01-06 08:05:14.3210717 +0000 UTC 0 0001-01-01 00:00:00 +0000 UTC 0}
Type: <nil>, value: <nil>, The operation completed successfully. 
result is not of custom type
```
i used wireshark to verify that the server is sending the correct response, but the results remain empty after which i tried the same read in cpp and got the following result.

![image](https://user-images.githubusercontent.com/122083313/210964355-d12ba9ce-074e-4216-babf-6f77e71c1cc5.png)

**Comment by awcullen** [comment]
I forgot to mention an important point!   When you register the custom type with the library, use the NodeID that corresponds to the BinaryEncodingID of the type.   This will be different than the NodeID of the variable or even the NodeID of the DataType.

With UAExpert, you can find the BinaryEncodingID by opening DataTypes...BaseDataType...Structures...[name of type]

Then find the DataTypeDefinition...DefaultEncodingID

![image](https://user-images.githubusercontent.com/11900570/211124745-23774e4f-73e1-43f1-9878-16b182c0d5bf.png)

**Comment by mark-resato** [comment]
i downloaded uaExpert and found the DataTypeDefinition

![image](https://user-images.githubusercontent.com/122083313/211266836-43c42059-9585-4754-96a2-04216e18848f.png)

Then i changed the nodeID in the init function to the following

```go
func init() {
    ua.RegisterBinaryEncodingID(
        reflect.TypeOf(CustomStruct{}),
        ua.NewExpandedNodeID(ua.ParseNodeID("ns=4;i=13")),
    )
}
```
wireshark shows that the server is returning the data

![image](https://user-images.githubusercontent.com/122083313/211267453-9cbed389-85c9-41a1-890e-748643c1447b.png)

But the output i get is still 

![image](https://user-images.githubusercontent.com/122083313/211267667-e564d162-ca6c-454d-b6df-6471c64b1e94.png)

**Comment by awcullen** [comment]
Please reveal the ExtensionObject's TypeID from the WireShark message.  It should match the DefaultEncodingId  "ns=4;i=13"

**Comment by awcullen** [comment]
I forgot the second rule:  custom types need to be registered using the Namespace URI.

```
func init() {
    ua.RegisterBinaryEncodingID(reflect.TypeOf(CustomStruct{}), ua.NewExpandedNodeID(ua.ParseNodeID("nsu=<your custom type's namespace uri>;i=14")))
}  
```

I really need to add some tests and examples for this!

**Comment by awcullen** [comment]
Fixed bug in type registry lookup. Added Example.

**Comment by mark-resato** [comment]
> Please reveal the ExtensionObject's TypeID from the WireShark message. It should match the DefaultEncodingId "ns=4;i=13"

this is the response the opcua server sends

![image](https://user-images.githubusercontent.com/122083313/212897177-90d7b9da-b99d-415d-995e-176fa8491be0.png)

**Comment by rjboer** [comment]
> server sends
Hi Andrew, 

Have you tried this with a Siemens PLC?

**Comment by awcullen** [comment]
Here is a program to read a custom structure from a S7-1500.
Please get v1.0.0 or later source using:  go get github.com/awcullen/opcua@v1.0.0
```
package main

import (
	"context"
	"fmt"
	"reflect"

	"github.com/awcullen/opcua/client"
	"github.com/awcullen/opcua/ua"
)

// This example demonstrates reading a variable with type of Simatic structure.
func main() {

	ctx := context.Background()

	// open a connection to opcua server of running S7-1500 PLC on local network.
	ch, err := client.Dial(
		ctx,
		"opc.tcp://192.168.254.44:4840",
		client.WithInsecureSkipVerify(), // skips verification of server certificate
	)
	if err != nil {
		fmt.Printf("Error opening client connection. %s\n", err.Error())
		return
	}

	// prepare read request
	req := &ua.ReadRequest{
		NodesToRead: []ua.ReadValueID{
			{
				// use backticks `` for Simatic nodeIDs with embedded quotes
				NodeID:      ua.ParseNodeID(`ns=3;s="Data_block_1"."PointA"`),
				AttributeID: ua.AttributeIDValue,
			},
		},
	}

	// send request to server. receive response or error
	res, err := ch.Read(ctx, req)
	if err != nil {
		fmt.Printf("Error reading TE_Vector. %s\n", err.Error())
		ch.Abort(ctx)
		return
	}

	// print results
	if custom, ok := res.Results[0].Value.(TE_Vector); ok {
		fmt.Printf("PointA:\n")
		fmt.Printf("  X: %f\n", custom.X)
		fmt.Printf("  Y: %f\n", custom.Y)
		fmt.Printf("  Z: %f\n", custom.Z)
	} else {
		fmt.Println("Error decoding TE_Vector.")
	}

	// close connection
	err = ch.Close(ctx)
	if err != nil {
		ch.Abort(ctx)
		return
	}

	// Output:
	// PointA:
	//   X: 1.000000
	//   Y: 2.000000
	//   Z: 3.000000
}

type TE_Vector struct {
	X float32
	Y float32
	Z float32
}

func init() {
	// use backticks `` for Simatic nodeIDs with embedded quotes
	ua.RegisterBinaryEncodingID(reflect.TypeOf(TE_Vector{}), ua.ParseExpandedNodeID(`nsu=http://www.siemens.com/simatic-s7-opcua;s=TE_"Vector"`))
}
```

**Comment by rjboer** [comment]
Hi Andrew, Thanks for checking!
We have a  case though where it doesn't work, we'll attach the tia portal project

**Comment by rjboer** [comment]
OK...we fixed it all!
For future reference...:
The thing is that the type definition is not similar to the shown in tools like UA expert... or through the browse function...
So far I have seen TD_"UDT_semver", TA_"UDT_semver" and "UDT_semver"
Through checks in the wireshark response it apperently is TE_"UDT_semver" <- which is weird, but works (and honestly just as Andrew explained above).

Will figure out why the browse gave a wrong type def. 

Furthermore Objects don't have values!, Variables are structs that can be queried... so you need to nest your UDT!!
In OPC UA, the node class "Object" represents a type of node that can have child nodes, properties, and methods. While the "Object" node itself does not have a value that can be read directly, you can still access its child nodes, properties, or methods, depending on their individual node classes and attributes
