### ISSUE TITLE
Get session info from srv

### ISSUE THREAD

**Issue by FranckEtienne** [awcullen/opcua#14]
I launch an OpcUa server with srv.ListenAndServe().

When an OpcUa client connect, I would have an event or retreive information.

I try with :
			if srv.ChannelManager().Len() > 0 {
				ssc, ret := srv.ChannelManager().Get(0)
				if ret {
					fmt.Printf("ssc: %d; SecurityMode: TODO\n", ssc.ChannelID())
				} else {
					fmt.Printf("ssc: NIL   !!!\n")
				}
			}

But, it's always retrun NIL :-(
What is the id in Get method: Get(id uint32)?
How can I retrieve it ?

Thank's a lot for your response and your job on OpcUa in Go :-)

**Comment by awcullen** [comment]
You pass the ChannelID to ChannelManger.Get(id uint32).
But the ChannelID's start at random number, not zero based.

I didn't plan for external access to channels and sessions or adding an event handler.  Good idea!

Did you know about the option to add server diagnostics?
```
srv, err := server.New(
		...
		server.WithServerDiagnostics(true),
)
```
This adds nodes to the server namespace, for each open session.

**Comment by FranckEtienne** [comment]
Hi Andrew,
What I want to do is to have info about a client which connect to the server.
It is the case with WithServerDiagnostics?
Is it possible to trust a client which connect with X509 certificates?
Thank's for your response and your work.

**Comment by awcullen** [comment]
Hi Franck,
If you add option WithServerDiagnostics, the server will add nodes to the namespace that can be observed using an OPC client such as UAExpert.

![image](https://user-images.githubusercontent.com/11900570/224594501-70dba9ea-15f9-4cb3-9e3c-54f0df8d52a6.png)

Also, in the release v1.0.2 you will find client may activate a session with X509Identity. Server must be provided with function that checks X509Identity, returning nil if authenticated.

```
server.WithAuthenticateX509IdentityFunc(func(userIdentity ua.X509Identity, applicationURI string, endpointURL string) error {
	cert, err := x509.ParseCertificate([]byte(userIdentity.Certificate))
	if err != nil {
		return ua.BadUserAccessDenied
	}
	log.Printf("Login %s from %s\n", cert.Subject, applicationURI)
	return nil
}),
```
