### ISSUE TITLE
CTT OPC UA fondation

### ISSUE THREAD

**Issue by FranckEtienne** [awcullen/opcua#15]
Is it in the roadmap to pass the CTT (compliance test tools) of the fondation OPC UA: https://opcfoundation.org/developer-tools/certification-test-tools/opc-ua-compliance-test-tool-uactt/ on opcua server part?

**Comment by awcullen** [comment]
Sadly, I am not a Coporate Member and can't use the test tool.

**Comment by FranckEtienne** [comment]
Hi Andrew,

Cool if you had CTT tools on your hand ;-)
I execute CTT on an OPC UA client, it was boring and long.
I expect it's more easy for server part ?

I'll use opcua client part to create an automate testing tool.
My leaders don't want that I use opcua server part in my project (no visibity on your code) :-(

To retreive CTT tools, it "just" necessary to sign as Logo Menber and purchase CTT:
The cost to purchase the CTT as a Logo Member is 1000 USD.

Behind the origin of my issue is to known:
- Are there some industry downloader which use Server part of opcua ?

**Comment by bearsh** [comment]
Hi @awcullen 
I'm also interested to know about the completeness of the server implementation. Right now, I have the build a OPC-UA server. I would really like to use your implementation as other parts of my software stack are already implemented in Go. this would make everything a lot easier.
Right know I experiment with linking my Go software against open62541 which works but is also some pain in the ass :unamused:

**Comment by awcullen** [comment]
I am making progress towards passing CTT tests.  But there are still many to tests go.

@bearsh, does your software write values to the server's nodes, or do you set the server's readvaluehandlers to return values from your software on request?  I'm curious if there's a better way, that's also golang friendly.
