### ISSUE TITLE
We can't acces response of OpenSecureChannel/CreateSession/ActivateSession with DIAL

### ISSUE THREAD

**Issue by FranckEtienne** [awcullen/opcua#18]
Method Dial proposed by awcullen/opcua is 3 OPCUA services combined : OpenSecureChannel, CreateSession and ActivateSession.
Each of theses 3 services aren't offered.

I can't have acces to server response: I would like to have access to ServiceResult and to RevisedSessionTimeout and MaxRequestMessageSize (from CreateSession).

Thank's for your job on OPCUA

**Comment by awcullen** [comment]
I added access for revised SessionTimeout and MaxRequestMessageSize.  If ServiceResult is not Good, then it is returned as error from the Dial function.  

Hope this helps.  Thanks for suggestion.
