### ISSUE TITLE
Dial return BadUnexpectedError rather than Bad_SecurityModeRejected when no security mode when ther is no match

### ISSUE THREAD

**Issue by FranckEtienne** [awcullen/opcua#19]
A client try to connect without security mode while server only accept securised session.
Dial return BadUnexpectedError but the response should be Bad_SecurityModeRejected.

It's appear here in client.go::Dial :
if selectedEndpoint == nil {
	return nil, ua.BadUnexpectedError
}

**Comment by awcullen** [comment]
Good idea. Thanks.
