### ISSUE TITLE
Arbitrary Extension Objects

### ISSUE THREAD

**Issue by szgeri** [awcullen/opcua#20]
Awesome work with the library, I really love it. I want to be able to read arbitrary Extension objects in the format of map[string]interface{}. Arrays too :) Do you have some ideas about where should I start, what would be the best approach that would fit in the whole idea of the architecture? Maybe you even have some code snippets? Thank you.

**Comment by CrowdHailer** [comment]
We would also make use of such functionality. Do you know if anyone has every done any further work on enabling it?
