### ISSUE TITLE
PLC behind router/vpn

### ISSUE THREAD

**Issue by rjboer** [awcullen/opcua#29]
I am facing an issue with a Golang OPC-UA client when trying to establish a connection with a PLC (S7-1515). The PLC is in a sub-network behind a router and has its own local IP address. 

In the Dial function of the OPC-UA client, I pass an endpointURL that points to the PLC. During the connection process, the client fetches available endpoints from the PLC using the GetEndpoints method. The client then sorts and selects one of these endpoints based on security levels and other criteria.

The issue arises when the client replaces the endpointURL I provided with one from the selected endpoint returned by GetEndpoints. This becomes problematic because the selected endpoint often has a local IP address, rendering it inaccessible from my network.

Suspected Cause:
I suspect that the problem might be due to the way the endpoints are ordered and selected within the Dial function. Specifically, it is this block of code that sets the endpointURL based on the selected endpoint:

Client.go, dial function

if selectedEndpoint == nil {
    return nil, ua.BadSecurityModeRejected
}
cli.endpointURL = selectedEndpoint.EndpointURL

My current fix is that if the passed endpointurl is totally unequal to the ordered/selected endpoint url -> then take the passed endpoint url. 
This works, but is not a nice solution

**Comment by rjboer** [comment]
It replaces the vpn ip address for instance 10.0.0.52 with 192.168.2.10

**Comment by awcullen** [comment]
This is a popular request.

I found that I have been too strict and OPCUA Part 4 says: 
"Clients should be prepared to replace the HostName returned in the EndpointDescription with the HostName or the IP addresses they used to call GetEndpoints."

"A client shall verify the HostName specified in the Server Certificate is the same as the HostName contained in the endpointUrl. Servers shall add all possible HostNames like MyHost and MyHost.local into the Server Certificate. This includes IP addresses of the host or the HostName exposed by a NAT router used to connect to the Server."

So please add the second address, 10.0.0.52, to the certificate that your PLC provides.   
    
![image](https://github.com/awcullen/opcua/assets/11900570/5dc5be02-3c8d-4e82-82fd-24791a0fe5be)

**Comment by awcullen** [comment]
Release v1.2.3 should allow the connection, if the server certificate contains the alternate IP address.  

If changing the server certificate is not possible, you could also specify the client option WithInsecureSkipVerify()
