### ISSUE TITLE
opcua server

### ISSUE THREAD

**Issue by lishuaia** [awcullen/opcua#3]
Hello, I would like to ask if the OPCUA server supports histroy-read?Can you guide me how to achieve it?

**Comment by awcullen** [comment]
Yes, and I am preparing an example.
The example server will support clients reading raw or aggregated data from historian.
The example will use Postgres database running in a docker container. 
You will be able to code an adapter to your own historian by implementing the interface here:
https://github.com/awcullen/opcua/blob/master/server/history_read_writer.go

**Comment by awcullen** [comment]
I prepared a working example of a OPC UA server that supports storing and querying historical data.
It uses Timescale, the open-source relational database for time-series and analytics.
You can find it in the repository here. https://github.com/awcullen/historian
