### ISSUE TITLE
Q: Monitor state of the connection [client]

### ISSUE THREAD

**Issue by Wafje** [awcullen/opcua#39]
Hi,

Is there a way to monitor the state of a connection on client side?
I would like to implement reconnect functionality and use this to log datapoints with nil values when the connnection to the OPC UA Server goes down.

**Comment by awcullen** [comment]
Hi,  
Most library methods, like client.Dial and client.Read, return a result or error.  If error is not nil, it will most likely be a ua.StatusCode. If the UA Server goes down while you are communicating, you should get an error after the request's TimeoutHint (default = 15 sec).

So if you get an error, you will most likely want to log datapoints with nil values, call client.Abort(),  sleep for a few seconds, and restart the function.

**Comment by Wafje** [comment]
Hi,
 
While this is indeed true for Dail and Read, I was mainly interested how this would work for subscriptions.
 
When looking at [the example](https://github.com/awcullen/opcua/blob/master/client/example_client_createsubscription_test.go) more in depth, I realized this library is a more low level than I initially assumed.

As is clear by running the example, the publish request would throw an error in case the connection goes down.
 
Thanks for the feedback and helping to clear this out.
