### ISSUE TITLE
problem of goroutine leakage

### ISSUE THREAD

**Issue by artemovechkin** [awcullen/opcua#43]
Hi!

When creating the server, NewSessionManager, NewSubscriptionManager, NewNamespaceManager
are created, three goroutines are created that will end on the closing channel, the channel is closed if the condition is triggered

```
func (srv *Server) Close() error {
	srv.Lock()
	if srv.state != ua.Server State Running {
		srv.Unlock()
		return ua.Bad Internal Error
	}
	srv.state = ua.Server State Shutdown
	srv.Unlock()
...
```

but it won't work if there were problems before ListenAndServe where this status is put in the ranking srv.state = ua.ServerStateRunning.

if you agree with this, then I am ready to open a Pull Request for an operational change.

Thank you!

**Comment by awcullen** [comment]
Thank you for reporting this.  I've rewritten Close() to always close the channel that stops the goroutines.
